<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>spring-ai-chat</artifactId>
    <version>0.0.1</version>
    <name>spring-ai-chat</name>
    <description>Spring AI Chat</description>
    <packaging>pom</packaging>

    <modules>
        <module>backend</module>
    </modules>

    <properties>
        <spring-ai.version>1.1.8</spring-ai.version>
        <junit-pioneer.version>2.3.0</junit-pioneer.version>
        <maven-compiler-plugin.version>3.12.1</maven-compiler-plugin.version>
        <maven-resources-plugin.version>3.3.0</maven-resources-plugin.version>
        <spring-boot.version>3.3.2</spring-boot.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>
